backend:
  name: git-gateway

media_folder: source/images/uploads
public_folder: /images/uploads

collections:
  - name: pages
    label: Pages
    files:
      - file: "data/pages/home.yml"
        label: Homepage
        name: home
        fields:
          - label: Inventory
            name: inventory
            widget: list
            fields:
              - {label: Name, name: name, widget: string}
              - {label: Source, name: source, widget: string}
              - {label: Amount, name: amount, widget: string}
              - {label: Image, name: image, widget: image}

  - name: settings
    label: Settings
    files:
      - file: data/settings/site.yml
        label: Site
        name: site
        fields:
          - label: Site Title
            name: site_title
            widget: string
